LARM_chain:
  settler_config: /LARM_chain/settler_config
  configs:
    tight_tol:
      settler:
        joint_names:
          - left_s0
          - left_s1
          - left_e0
          - left_e1
          - left_w0
          - left_w1
          - left_w2
        tolerances:
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
        max_step: 1.0
        cache_size: 1500
RARM_chain:
  settler_config: /RARM_chain/settler_config
  configs:
    tight_tol:
      settler:
        joint_names:
          - right_s0
          - right_s1
          - right_e0
          - right_e1
          - right_w0
          - right_w1
          - right_w2
        tolerances:
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
          - 0.002
        max_step: 1.0
        cache_size: 1500
head_chain:
  settler_config: /head_chain/settler_config
  configs:
    tight_tol:
      settler:
        joint_names:
          - head_nod
          - head_pan
        tolerances:
          - 0.002
          - 0.002
        max_step: 1.0
        cache_size: 1500
