LARM_controller:
  topic: /robot/limb/left/command_joint_position
  joint_names:
    - left_s0
    - left_s1
    - left_e0
    - left_e1
    - left_w0
    - left_w1
    - left_w2
RARM_controller:
  topic: /robot/limb/right/command_joint_position
  joint_names:
    - right_s0
    - right_s1
    - right_e0
    - right_e1
    - right_w0
    - right_w1
    - right_w2
head_controller:
  topic: /robot/head/head_pan
  joint_names:
    - head_nod
    - head_pan
