
base_link: base

sensors:

  chains:
    LARM_chain:
      root: base
      tip: left_hand
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    RARM_chain:
      root: base
      tip: right_hand
      cov:
       joint_angles: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    head_chain:
      root: base
      tip: head
      cov:
       joint_angles: [0.01, 0.01]
      gearing: [1.0, 1.0]
  rectified_cams:
    head_camera:
      chain_id: RARM_chain  #TODO: get rid of this
      frame_id: right_hand_camera_rgb_optical_frame
      baseline_shift: 0.0
#      baseline_rgbd: 0.075 ## comment out if we run all_pipelines.launch with use_kinect
      f_shift: 0.0
      cx_shift: 0.0
      cy_shift: 0.0
      cov: {u: 0.25, v: 0.25, x: 0.25}

  tilting_lasers: {}

checkerboards:
  mmurooka_board:
    corners_x: 6
    corners_y: 5
    spacing_x: 0.03
    spacing_y: 0.03

transforms:
  head_chain_cb:   [0, 0, 0, 0, 0, 0]
  # LARM_chain_cb:   [0.128, 0, 0.075, 0, 0, 0]
  # RARM_chain_cb:   [0.128, 0, 0.075, 0, 0, 0]

#default_floating_initial_pose: [0, 0, 0, -1.2092, 1.2092, -1.2092]
#default_floating_initial_pose: [0, 0, 0, 0, 0, 0]
# xyz: [-0.002956968077825933, 0.16898467170866147, -0.20050853695600393]
# rpy: (-0.04425102767135782, 0.01876497698337332, -0.019873022766080706)

initial_poses: "/tmp/baxter_calibration/initial_poses.yaml"
